export const UNIT_SYMBOL = {
  GRM: 'g',
  MC: 'mcg',
  LTR: 'l',
  KGM: 'kg',
  MLT: 'ml',
  CLT: 'cl',
  KJO: 'kJ',
  E14: 'kcal',
  MGM: 'mg',
}

export const NUTRIENT_NAME_OVERRIDE = {
  en: {
    'ENER-': 'Energy',
    FAT: 'Fat',
    FASAT: 'of which saturates',
    'CHO-': 'Carbohydrate',
    SUGAR: 'of which sugars',
    'PRO-': 'Protein',
    SALTEQ: 'Salt',
    NACL: 'Salt',
  },
  fi: {
    'ENER-': 'Energia',
    FAT: 'Rasva',
    FASAT: 'josta tyydyttyneitä rasvoja',
    'CHO-': 'Hiilihydraatit',
    SUGAR: 'josta sokereita',
    'PRO-': 'Proteiini',
    SALTEQ: 'Suola',
    NACL: 'Suola',
  },
  pt: {
    'ENER-': '#Energy',
    FAT: '#Fat',
    FASAT: '#of which saturates',
    'CHO-': '#Carbohydrate',
    SUGAR: '#of which sugars',
    'PRO-': '#Protein',
    SALTEQ: '#Salt',
    NACL: '#Salt',
  },
  es: {
    'ENER-': '#Energy',
    FAT: '#Fat',
    FASAT: '#of which saturates',
    'CHO-': '#Carbohydrate',
    SUGAR: '#of which sugars',
    'PRO-': '#Protein',
    SALTEQ: '#Salt',
    NACL: '#Salt',
  },
}
