#!/bin/bash

TENANT_NAME=$2
SERVICE_NAME=$1-client-$2

TAG=$(cat package.json |
  grep version |
  head -1 |
  awk -F: '{ print $2 }' |
  sed 's/[",]//g' |
  tr -d '[[:space:]]')

IMAGE_NAME=${SERVICE_NAME}:${TAG}
IMAGE=${DOCKER_REGISTRY}/${IMAGE_NAME}

API_KEY_NAME="${TENANT_NAME}_api_key"
ORGANIZATION_ID_NAME="${TENANT_NAME}_organization_id"
API_URL_NAME="${TENANT_NAME}_api_url"
SHOPPER_API_URL_NAME="${TENANT_NAME}_shopper_api_url"
CLIENT_SECRET_NAME="${TENANT_NAME}_client_secret"
DEFAULT_STORE_NAME="${TENANT_NAME}_default_store_id"
LOOKUP_COUNTRY_CODE_NAME="${TENANT_NAME}_lookup_country_code"
CLUSTER_NAME="${TENANT_NAME}_cluster"
GOOGLE_TAG_MANAGER_KEY_NAME="${TENANT_NAME}_google_tag_manager_key"
GOOGLE_MAP_KEY_NAME="${TENANT_NAME}_google_map_key"
FACEBOOK_DOMAIN_VERIFICATION_NAME="${TENANT_NAME}_facebook_domain_verification"
BRAND_THEME_NAME="${TENANT_NAME}_brand_theme"
SITE_URL_NAME="${TENANT_NAME}_site_url"
NEXTAUTH_URL_NAME="${TENANT_NAME}_nextauth_url"
AUTH_TENANT_NAME_NAME="${TENANT_NAME}_auth_tenant_name"
AUTH_TENANT_ID_NAME="${TENANT_NAME}_auth_tenant_id"
AUTH_CLIENT_ID_NAME="${TENANT_NAME}_auth_client_id"
AUTH_CLIENT_SECRET_NAME="${TENANT_NAME}_auth_client_secret"
AUTH_LOGIN_FLOW_NAME="${TENANT_NAME}_auth_login_flow"
AUTH_PROFILE_EDIT_URL_NAME="${TENANT_NAME}_auth_profile_edit_url"
AUTH_PASSWORD_RESET_URL_NAME="${TENANT_NAME}_auth_password_reset_url"


DG_API_KEY=${!API_KEY_NAME}
DG_ORGANIZATION_ID=${!ORGANIZATION_ID_NAME}
DG_API_URL=${!API_URL_NAME}
SHOPPER_API_URL=${!SHOPPER_API_URL_NAME}
DEFAULT_STORE_ID=${!DEFAULT_STORE_NAME}
LOOKUP_COUNTRY_CODE=${!LOOKUP_COUNTRY_CODE_NAME}
CLUSTER=${!CLUSTER_NAME}
GOOGLE_TAG_MANAGER_KEY=${!GOOGLE_TAG_MANAGER_KEY_NAME}
GOOGLE_MAP_KEY=${!GOOGLE_MAP_KEY_NAME}
FACEBOOK_DOMAIN_VERIFICATION=${!FACEBOOK_DOMAIN_VERIFICATION_NAME}
BRAND_THEME=${!BRAND_THEME_NAME}
SITE_URL=${!SITE_URL_NAME}
NEXTAUTH_URL=${!NEXTAUTH_URL_NAME}
AUTH_TENANT_NAME=${!AUTH_TENANT_NAME_NAME}
AUTH_TENANT_ID=${!AUTH_TENANT_ID_NAME}
AUTH_CLIENT_ID=${!AUTH_CLIENT_ID_NAME}
AUTH_CLIENT_SECRET=${!AUTH_CLIENT_SECRET_NAME}
AUTH_LOGIN_FLOW=${!AUTH_LOGIN_FLOW_NAME}
AUTH_PROFILE_EDIT_URL=${!AUTH_PROFILE_EDIT_URL_NAME}
AUTH_PASSWORD_RESET_URL=${!AUTH_PASSWORD_RESET_URL_NAME}


docker build \
  --build-arg "BUILD_DATE=$(date -u '+%Y-%m-%dT%H:%M:%SZ')" \
  --build-arg "BUILD_NUMBER=${TAG}" \
  --build-arg "BUILD_IMAGE=${IMAGE_NAME}" \
  --build-arg "DG_API_KEY=${DG_API_KEY}" \
  --build-arg "DG_ORGANIZATION_ID=${DG_ORGANIZATION_ID}" \
  --build-arg "DG_API_URL=${DG_API_URL}" \
  --build-arg "SHOPPER_API_URL=${SHOPPER_API_URL}" \
  --build-arg "DEFAULT_STORE_ID=${DEFAULT_STORE_ID}" \
  --build-arg "LOOKUP_COUNTRY_CODE=${LOOKUP_COUNTRY_CODE}" \
  --build-arg "CLUSTER=${CLUSTER}" \
  --build-arg "GOOGLE_TAG_MANAGER_KEY=${GOOGLE_TAG_MANAGER_KEY}" \
  --build-arg "GOOGLE_MAP_KEY=${GOOGLE_MAP_KEY}" \
  --build-arg "FACEBOOK_DOMAIN_VERIFICATION=${FACEBOOK_DOMAIN_VERIFICATION}" \
  --build-arg "BRAND_THEME=${BRAND_THEME}" \
  --build-arg "SITE_URL=${SITE_URL}" \
  --build-arg "NEXTAUTH_URL=${NEXTAUTH_URL}" \
  --build-arg "AUTH_TENANT_NAME=${AUTH_TENANT_NAME}" \
  --build-arg "AUTH_TENANT_ID=${AUTH_TENANT_ID}" \
  --build-arg "AUTH_CLIENT_ID=${AUTH_CLIENT_ID}" \
  --build-arg "AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}" \
  --build-arg "AUTH_LOGIN_FLOW=${AUTH_LOGIN_FLOW}" \
  --build-arg "AUTH_PROFILE_EDIT_URL=${AUTH_PROFILE_EDIT_URL}" \
  --build-arg "AUTH_PASSWORD_RESET_URL=${AUTH_PASSWORD_RESET_URL}" \
  -t ${IMAGE} .

docker push ${IMAGE}
